### PR TITLE
Fix check if document & window are defined

### PR DESCRIPTION
**Pull request by CanRau**
Okay this seems to be working fine

I removed the `typeof navigator !== 'undefined'` as it shouldn't be necessary anymore, right?

### CODE REVIEW

**Comment by ai** [comment]
> I removed the typeof navigator !== 'undefined' as it shouldn't be necessary anymore, right?

:+1: We do not need it anymore

You mentioned about some RN warning for `window`. Did you fixed it too?

**Comment by CanRau** [comment]
So after commenting all window event listeners out, like
```js
if (typeof window !== 'undefined') {
  // window.removeEventListener('storage', this.onStorage);
}
```
in client.js and cross-tab-client.js, then it'll show the actual start screen for a few seconds and then 
Screenshot_20191105-143637_mobileRnTs
No idea why the `typeof window !== 'undefined'` work in reconnect.js but not in client.js and cross-tab-client.js

**Comment by ai** [comment]
What error do you have without this fix?

(Maybe RN put a different object in `window` like `{ }`)

**Comment by ai** [comment]
I think `Logux error: undefined` it is a another error. We can start to fix it after fixing the problem with `reconnect` and `windows`. Is it OK?

**Comment by CanRau** [comment]
So reconnect works fine, no more errors related to window or document from reconnect.js

the above mentions are in `@logux/client/client.js` and `@logux/client/cross-tab-client.js`

**Comment by CanRau** [comment]
> What error do you have without this fix?
> 
> (Maybe RN put a different object in `window` like `{ }`)

Without commenting those lines I get `TypeError: window.addEventListener is not a function`

**Comment by ai** [comment]
> Without commenting those lines I get TypeError: window.addEventListener is not a function

Hm, seems like RN set an empty object there. Can you change the check to `typeof window !== 'undefined' && window.addEventListener`?

**Comment by CanRau** [comment]
That works, it's not complaining about `window.removeEventListener('unload', this.onUnload)` but maybe because it's in the `destroy` function and hasn't been called yet

Still not sure why it's working in reconnect.js without the extra check, a friend told me that it might be due to RN running things in different threads where the main thread is a node instance and the renderer are window like probably containing a window object without the event listener functions

**Comment by ai** [comment]
Yeap, we may need to fix Logux Client too https://github.com/logux/client/blob/master/client.js#L396

Can you push the `typeof window !== 'undefined' && window.addEventListener` fix? I will relase it.

**Comment by CanRau** [comment]
I probably shouldn't use CrossTabClient anyway in RN, so I'll add the `typeof window !== 'undefined' && window.addEventListener` only to client.js right?

**Comment by ai** [comment]
I think it will be nice to have `window` checks for `cross-tab-client` too. You are right that it is not important for RN, but it will be good for SSR (let’s add checks everywhere if we found that we need them).

**Comment by ai** [comment]
BTW, do you have Twitter account to mention you in release tweet?

**Comment by CanRau** [comment]
sure https://twitter.com/canrau

**Comment by ai** [comment]
Can you push the `typeof window !== 'undefined' && window.addEventListener` fix to this repo as well? (I can fix it by my own, but if you will fix it, we will have shinny git history =^_^=)

**Comment by CanRau** [comment]
hehe sure 👍 I'm note sure about `document.addEventlistener` so I added it just in case, if you think it's unnecessary I can remove it

**Comment by ai** [comment]
Thanks. Released in 0.3.4. Now it is time to release Logux Client (I need to update ESLint config, so it takes a while).

**Pull request merged**
